"use client";

import { useQuery } from "@tanstack/react-query";
import { BellRingIcon, CalendarDaysIcon, ExternalLinkIcon, RefreshCwIcon } from "lucide-react";
import { useLocale } from "@/components/locale-provider";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import type { CampusUpdates } from "@/lib/types";

export function UpdatesFeed() {
  const { locale, pick } = useLocale();
  const query = useQuery({ queryKey: ["student", "updates", "feed"], queryFn: async () => { const response = await fetch("/api/student/updates?limit=100"); if (!response.ok) throw new Error("Updates unavailable"); return response.json() as Promise<CampusUpdates>; } });
  return <main className="h-full overflow-y-auto"><div className="mx-auto max-w-4xl p-4 sm:p-6 lg:p-8"><div className="mb-6 flex items-end justify-between gap-3"><div><h1 className="text-2xl font-semibold tracking-tight">{pick({ tr: "Kampüs güncellemeleri", en: "Campus updates" })}</h1><p className="mt-1 text-sm text-muted-foreground">{pick({ tr: "Bölümün, öğrenim düzeyin ve ilgi alanlarına göre sıralanır.", en: "Ranked for your department, degree level, and interests." })}</p></div><Button variant="outline" size="sm" onClick={() => void query.refetch()} disabled={query.isFetching}><RefreshCwIcon className={query.isFetching ? "animate-spin" : ""} />{pick({ tr: "Yenile", en: "Refresh" })}</Button></div>{query.isLoading ? <div className="space-y-3">{Array.from({ length: 5 }).map((_, index) => <Skeleton key={index} className="h-32 rounded-xl" />)}</div> : query.error ? <Card><CardContent className="py-10 text-center text-sm text-destructive">{query.error.message}</CardContent></Card> : query.data?.items.length ? <div className="space-y-3">{query.data.items.map((item) => <Card key={item.id} className="surface-raised border-0 ring-1 ring-foreground/8"><CardContent className="flex gap-4"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-primary/10 text-primary">{item.type === "event" || item.type === "calendar" ? <CalendarDaysIcon className="size-4" /> : <BellRingIcon className="size-4" />}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><Badge variant="outline">{item.type.replaceAll("_", " ")}</Badge>{item.origin === "mail_fact" ? <Badge variant="secondary">Email</Badge> : null}</div><h2 className="mt-2 font-semibold">{item.title}</h2>{item.summary ? <p className="mt-1 text-sm leading-6 text-muted-foreground">{item.summary}</p> : null}<div className="mt-3 flex flex-wrap items-center gap-3 text-xs text-muted-foreground"><span>{item.source}</span>{item.starts_at ? <span>{new Intl.DateTimeFormat(locale === "tr" ? "tr-TR" : "en-US", { dateStyle: "medium", timeStyle: "short" }).format(new Date(item.starts_at))}</span> : null}{item.url ? <a href={item.url} target="_blank" rel="noreferrer" className="ml-auto inline-flex items-center gap-1 font-medium text-primary hover:underline">{pick({ tr: "Kaynağı aç", en: "Open source" })}<ExternalLinkIcon className="size-3" /></a> : null}</div></div></CardContent></Card>)}</div> : <Card><CardContent className="py-12 text-center"><BellRingIcon className="mx-auto mb-3 size-5 text-muted-foreground" /><p className="font-medium">{pick({ tr: "Şu anda yeni güncelleme yok", en: "No new updates right now" })}</p></CardContent></Card>}</div></main>;
}
