"use client";

import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BookOpenIcon, DatabaseZapIcon, EyeIcon, LinkIcon, PlusIcon, RefreshCwIcon, RocketIcon } from "lucide-react";
import { toast } from "sonner";
import { useLocale } from "@/components/locale-provider";
import { EmptyState, ErrorState, PanelHeader, StatusBadge, formatDate } from "@/components/admin/admin-shared";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Textarea } from "@/components/ui/textarea";
import { adminGet, adminMutate } from "@/lib/admin/client";
import type { AdminPrincipal, CourseGroup, KnowledgeSource, KnowledgeSourceDetail } from "@/lib/admin/types";
import { cn } from "@/lib/utils";

const SOURCE_KINDS = ["drupal", "html_page", "html_table", "rss", "ical", "json", "pdf", "approved_social", "curated"] as const;

export function KnowledgePanel({ principal, title, description }: { principal: AdminPrincipal; title: string; description: string }) {
  const { locale, pick } = useLocale();
  const client = useQueryClient();
  const [creating, setCreating] = useState(false);
  const [selected, setSelected] = useState<KnowledgeSource | null>(null);
  const [addingGroup, setAddingGroup] = useState(false);
  const sources = useQuery({ queryKey: ["admin", "sources"], queryFn: () => adminGet<{ items: KnowledgeSource[] }>("sources") });
  const groups = useQuery({ queryKey: ["admin", "course-groups"], queryFn: () => adminGet<{ items: CourseGroup[] }>("course-groups") });
  const refresh = () => void client.invalidateQueries({ queryKey: ["admin"] });
  const installDefaults = useMutation({ mutationFn: () => adminMutate<{ created: unknown[] }>("source-templates/install-defaults", "POST", {}), onSuccess: (data) => { toast.success(`${data.created.length} ${pick({ tr: "önerilen taslak eklendi", en: "recommended drafts added" })}`); refresh(); }, onError: (error) => toast.error(error.message) });

  return <>
    <PanelHeader title={title} description={description} actions={<><Button variant="outline" size="sm" onClick={refresh}><RefreshCwIcon />{pick({ tr: "Yenile", en: "Refresh" })}</Button>{principal.permissions.includes("knowledge:write") ? <><Button variant="outline" size="sm" disabled={installDefaults.isPending} onClick={() => installDefaults.mutate()}><DatabaseZapIcon />{pick({ tr: "ODTÜ taslaklarını ekle", en: "Add METU drafts" })}</Button><Button size="sm" onClick={() => setCreating(true)}><PlusIcon />{pick({ tr: "Kaynak ekle", en: "Add source" })}</Button></> : null}</>} />
    <div className="space-y-6">
      {sources.isLoading ? <Skeleton className="h-72 rounded-xl" /> : sources.error ? <ErrorState error={sources.error} retry={() => void sources.refetch()} /> : <Card className="surface-raised border-0 py-0 ring-1 ring-foreground/8"><CardContent className="px-0">{sources.data?.items.length ? <Table><TableHeader className="bg-muted/45"><TableRow><TableHead className="pl-4">{pick({ tr: "Kaynak", en: "Source" })}</TableHead><TableHead>{pick({ tr: "Durum", en: "Status" })}</TableHead><TableHead>{pick({ tr: "Kayıtlar", en: "Records" })}</TableHead><TableHead>{pick({ tr: "Son başarı", en: "Last success" })}</TableHead><TableHead className="pr-4 text-right">{pick({ tr: "İşlemler", en: "Actions" })}</TableHead></TableRow></TableHeader><TableBody>{sources.data.items.map((source) => <TableRow key={source.id}><TableCell className="pl-4"><p className="font-medium">{source.name}</p><p className="max-w-96 truncate text-xs text-muted-foreground">{source.url ?? source.kind}</p></TableCell><TableCell><StatusBadge value={source.status} /></TableCell><TableCell><span className="font-semibold tabular-nums">{source.records ?? 0}</span><span className="ml-2 text-xs text-muted-foreground">· {source.revisions ?? 0} rev</span></TableCell><TableCell className={cn("text-muted-foreground", source.last_error && "text-destructive")}>{source.last_error ? source.last_error : formatDate(source.last_success_at, locale)}</TableCell><TableCell className="pr-4 text-right"><Button variant="ghost" size="sm" onClick={() => setSelected(source)}><EyeIcon />{pick({ tr: "Yönet", en: "Manage" })}</Button></TableCell></TableRow>)}</TableBody></Table> : <EmptyState title={pick({ tr: "Henüz kaynak yok", en: "No sources yet" })} description={pick({ tr: "Akademik takvim, duyurular, etkinlikler ve hizmet durumları için bir kaynak ekleyin.", en: "Add a source for calendars, announcements, events, or service status." })} icon={<DatabaseZapIcon className="size-4" />} />}</CardContent></Card>}

      <div>
        <div className="mb-3 flex items-center justify-between"><div><h2 className="text-lg font-semibold">{pick({ tr: "Korumalı ders grupları", en: "Protected course groups" })}</h2><p className="text-sm text-muted-foreground">{pick({ tr: "Bağlantılar yalnızca güncel kayıt doğrulamasından sonra öğrenciye gösterilir.", en: "Links are revealed only after current enrollment is verified." })}</p></div>{principal.permissions.includes("groups:write") ? <Button variant="outline" size="sm" onClick={() => setAddingGroup(true)}><LinkIcon />{pick({ tr: "Grup ekle", en: "Add group" })}</Button> : null}</div>
        {groups.isLoading ? <Skeleton className="h-32 rounded-xl" /> : groups.error ? <ErrorState error={groups.error} retry={() => void groups.refetch()} /> : <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{groups.data?.items.map((group) => <Card key={group.id} className="surface-raised border-0 ring-1 ring-foreground/8"><CardHeader><div className="flex items-start justify-between gap-2"><div><CardTitle>{group.course_code}{group.section ? ` · ${group.section}` : ""}</CardTitle><CardDescription>{group.term}</CardDescription></div><StatusBadge value={group.active ? "active" : "stopped"} /></div></CardHeader><CardContent><p className="text-xs text-muted-foreground">{group.valid_until ? `${pick({ tr: "Geçerli olduğu tarih", en: "Valid until" })}: ${formatDate(group.valid_until, locale)}` : pick({ tr: "Süre sonu yok", en: "No expiry" })}</p></CardContent></Card>)}{!groups.data?.items.length ? <Card className="md:col-span-2 xl:col-span-3"><EmptyState title={pick({ tr: "Ders grubu yok", en: "No course groups" })} /></Card> : null}</div>}
      </div>
    </div>
    <CreateSourceDialog open={creating} onOpenChange={setCreating} onDone={() => { setCreating(false); refresh(); }} />
    <SourceDialog source={selected} onOpenChange={(open) => !open && setSelected(null)} onDone={refresh} />
    <CreateGroupDialog open={addingGroup} onOpenChange={setAddingGroup} onDone={() => { setAddingGroup(false); refresh(); }} />
  </>;
}

function CreateSourceDialog({ open, onOpenChange, onDone }: { open: boolean; onOpenChange: (open: boolean) => void; onDone: () => void }) {
  const { pick } = useLocale();
  const [name, setName] = useState(""); const [kind, setKind] = useState<(typeof SOURCE_KINDS)[number]>("drupal"); const [url, setUrl] = useState(""); const [recordType, setRecordType] = useState("announcement"); const [config, setConfig] = useState("{}");
  const mutation = useMutation({ mutationFn: () => adminMutate("sources", "POST", { name, kind, url: url || null, language: "tr", authority: 70, audience: {}, schedule_seconds: 3600, config: { ...JSON.parse(config), defaults: { ...(JSON.parse(config).defaults ?? {}), record_type: recordType } } }), onSuccess: () => { toast.success(pick({ tr: "Taslak kaynak oluşturuldu", en: "Draft source created" })); setName(""); setUrl(""); setConfig("{}"); onDone(); }, onError: (error) => toast.error(error.message) });
  let validConfig = true; try { JSON.parse(config); } catch { validConfig = false; }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-2xl"><DialogHeader><DialogTitle>{pick({ tr: "Kampüs kaynağı ekle", en: "Add campus source" })}</DialogTitle><DialogDescription>{pick({ tr: "Kaynak taslak olarak kaydedilir; önizleme ve yayınlama ayrı adımlardır.", en: "The source is saved as a draft; preview and publish are separate steps." })}</DialogDescription></DialogHeader><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label>{pick({ tr: "Ad", en: "Name" })}</Label><Input value={name} onChange={(event) => setName(event.target.value)} /></div><div className="space-y-2"><Label>{pick({ tr: "Kaynak türü", en: "Source type" })}</Label><Select value={kind} onValueChange={(value) => setKind((value ?? "drupal") as typeof kind)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{SOURCE_KINDS.map((value) => <SelectItem key={value} value={value}>{value.replaceAll("_", " ")}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2 sm:col-span-2"><Label>URL</Label><Input value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://…" /></div><div className="space-y-2"><Label>{pick({ tr: "İçerik türü", en: "Content type" })}</Label><Select value={recordType} onValueChange={(value) => setRecordType(value ?? "announcement")}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["announcement", "calendar", "event", "service_status", "guide", "course", "policy"].map((value) => <SelectItem key={value} value={value}>{value.replaceAll("_", " ")}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2 sm:col-span-2"><Label>{pick({ tr: "Gelişmiş çıkarma ayarları", en: "Advanced extraction settings" })}</Label><Textarea className="min-h-28 font-mono text-xs" value={config} onChange={(event) => setConfig(event.target.value)} /><p className={cn("text-xs text-muted-foreground", !validConfig && "text-destructive")}>{validConfig ? pick({ tr: "Seçiciler ve alan eşlemeleri için isteğe bağlı JSON.", en: "Optional JSON for selectors and field mappings." }) : pick({ tr: "Geçerli JSON gerekli.", en: "Valid JSON is required." })}</p></div></div><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>{pick({ tr: "Vazgeç", en: "Cancel" })}</Button><Button disabled={name.trim().length < 2 || !validConfig || mutation.isPending} onClick={() => mutation.mutate()}>{pick({ tr: "Taslağı oluştur", en: "Create draft" })}</Button></DialogFooter></DialogContent></Dialog>;
}

function SourceDialog({ source, onOpenChange, onDone }: { source: KnowledgeSource | null; onOpenChange: (open: boolean) => void; onDone: () => void }) {
  const { pick } = useLocale();
  const query = useQuery({ queryKey: ["admin", "source", source?.id], queryFn: () => adminGet<KnowledgeSourceDetail>(`sources/${source!.id}`), enabled: Boolean(source) });
  const revision = query.data?.revision_history[0];
  const preview = useMutation({ mutationFn: () => adminMutate<{ count: number }>(`sources/${source!.id}/revisions/${revision!.id}/preview`, "POST", {}), onSuccess: (data) => toast.success(`${data.count} ${pick({ tr: "kayıt önizlendi", en: "records previewed" })}`), onError: (error) => toast.error(error.message) });
  const publish = useMutation({ mutationFn: () => adminMutate(`sources/${source!.id}/revisions/${revision!.id}/publish`, "POST", {}), onSuccess: () => { toast.success(pick({ tr: "Kaynak yayınlandı ve içe aktarma sıraya alındı", en: "Source published and ingestion queued" })); onDone(); void query.refetch(); }, onError: (error) => toast.error(error.message) });
  const ingest = useMutation({ mutationFn: () => adminMutate(`sources/${source!.id}/ingest`, "POST", {}), onSuccess: () => { toast.success(pick({ tr: "Yenileme sıraya alındı", en: "Refresh queued" })); onDone(); }, onError: (error) => toast.error(error.message) });
  return <Dialog open={Boolean(source)} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-2xl"><DialogHeader><DialogTitle>{source?.name}</DialogTitle><DialogDescription>{source?.url ?? source?.kind}</DialogDescription></DialogHeader>{query.isLoading ? <Skeleton className="h-52" /> : revision ? <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl border bg-muted/25 p-3"><p className="text-xs text-muted-foreground">{pick({ tr: "Son revizyon", en: "Latest revision" })}</p><p className="mt-1 font-semibold">#{revision.revision}</p></div><div className="rounded-xl border bg-muted/25 p-3"><p className="text-xs text-muted-foreground">{pick({ tr: "Doğrulama", en: "Validation" })}</p><div className="mt-1"><StatusBadge value={revision.validation.ok ? "success" : "failed"} /></div></div><div className="rounded-xl border bg-muted/25 p-3"><p className="text-xs text-muted-foreground">{pick({ tr: "Durum", en: "Status" })}</p><div className="mt-1"><StatusBadge value={revision.status} /></div></div></div>{revision.validation.errors.length ? <div className="rounded-xl border border-destructive/25 bg-destructive/5 p-3 text-sm text-destructive">{revision.validation.errors.join(" · ")}</div> : null}<pre className="max-h-48 overflow-auto rounded-xl border bg-muted/25 p-3 text-xs">{JSON.stringify(revision.config, null, 2)}</pre></div> : <EmptyState title={pick({ tr: "Revizyon bulunamadı", en: "No revision found" })} />}<DialogFooter className="flex-wrap"><Button variant="outline" disabled={!revision || preview.isPending} onClick={() => preview.mutate()}><EyeIcon />{pick({ tr: "Önizle", en: "Preview" })}</Button><Button variant="outline" disabled={!source?.active_revision_id || ingest.isPending} onClick={() => ingest.mutate()}><RefreshCwIcon />{pick({ tr: "Şimdi yenile", en: "Refresh now" })}</Button><Button disabled={!revision?.validation.ok || publish.isPending} onClick={() => publish.mutate()}><RocketIcon />{pick({ tr: "Yayınla", en: "Publish" })}</Button></DialogFooter></DialogContent></Dialog>;
}

function CreateGroupDialog({ open, onOpenChange, onDone }: { open: boolean; onOpenChange: (open: boolean) => void; onDone: () => void }) {
  const { pick } = useLocale(); const [term, setTerm] = useState(""); const [course, setCourse] = useState(""); const [section, setSection] = useState(""); const [url, setUrl] = useState("");
  const mutation = useMutation({ mutationFn: () => adminMutate("course-groups", "POST", { term, course_code: course, section: section || null, invite_url: url, eligibility: {} }), onSuccess: () => { toast.success(pick({ tr: "Korumalı grup eklendi", en: "Protected group added" })); onDone(); }, onError: (error) => toast.error(error.message) });
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>{pick({ tr: "Ders grubu ekle", en: "Add course group" })}</DialogTitle><DialogDescription>{pick({ tr: "Bağlantı şifrelenir ve arama dizinine eklenmez.", en: "The invite is encrypted and never added to search." })}</DialogDescription></DialogHeader><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label>{pick({ tr: "Dönem", en: "Term" })}</Label><Input value={term} onChange={(event) => setTerm(event.target.value)} placeholder="2026-2027-fall" /></div><div className="space-y-2"><Label>{pick({ tr: "Ders kodu", en: "Course code" })}</Label><Input value={course} onChange={(event) => setCourse(event.target.value)} placeholder="CENG213" /></div><div className="space-y-2"><Label>{pick({ tr: "Şube (isteğe bağlı)", en: "Section (optional)" })}</Label><Input value={section} onChange={(event) => setSection(event.target.value)} /></div><div className="space-y-2 sm:col-span-2"><Label>{pick({ tr: "WhatsApp davet bağlantısı", en: "WhatsApp invite link" })}</Label><Input value={url} onChange={(event) => setUrl(event.target.value)} type="url" /></div></div><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>{pick({ tr: "Vazgeç", en: "Cancel" })}</Button><Button disabled={term.length < 3 || course.length < 2 || url.length < 10 || mutation.isPending} onClick={() => mutation.mutate()}><BookOpenIcon />{pick({ tr: "Grubu ekle", en: "Add group" })}</Button></DialogFooter></DialogContent></Dialog>;
}
